// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg67kXTbl7GIgxkXODCio8nVd9gmJeqlY',
    appId: '1:867883458042:android:16b0427d1bc80272f01843',
    messagingSenderId: '867883458042',
    projectId: 'fir-function-api-3a7c7',
    databaseURL: 'https://fir-function-api-3a7c7-default-rtdb.firebaseio.com',
    storageBucket: 'fir-function-api-3a7c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyVs6Y2CbWlWM8SympOr-8ZLEp1VKhM6k',
    appId: '1:867883458042:ios:a80d815cc4036ad4f01843',
    messagingSenderId: '867883458042',
    projectId: 'fir-function-api-3a7c7',
    databaseURL: 'https://fir-function-api-3a7c7-default-rtdb.firebaseio.com',
    storageBucket: 'fir-function-api-3a7c7.appspot.com',
    iosBundleId: 'com.example.toDoLocal',
  );
}
